<a href="https://colab.research.google.com/github/Rishsing73/rishsing73.github.io/blob/master/multiclass_for_NumerAI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pandas sklearn numerapi
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from keras.models import Sequential
from keras.preprocessing.image import ImageDataGenerator
from keras.layers import BatchNormalization
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten
from keras.utils import normalize, to_categorical


In [2]:
tour_datalink = 'https://numerai-public-datasets.s3-us-west-2.amazonaws.com/latest_numerai_tournament_data.csv.xz'
train_datalink = 'https://numerai-public-datasets.s3-us-west-2.amazonaws.com/latest_numerai_training_data.csv.xz'
df_train = pd.read_csv(train_datalink, ) #download the training data and keep only the first 50,000 rows
df_tour = pd.read_csv(tour_datalink, )

In [6]:
features = [c for c in df_train if c.startswith("feature")]
X_train =df_train[features].values
Y_train = df_train['target'].values
test = df_tour[df_tour.data_type == 'validation'].copy()
X_test = test[features].values
Y_test = test['target'].values

In [19]:
Y_tr = np.zeros((len(Y_train),5))
# for i in range(len(Y_train)):
  # if Y_train[i] == 0.25


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       ...,
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
help(to_categorical)

Help on function to_categorical in module tensorflow.python.keras.utils.np_utils:

to_categorical(y, num_classes=None, dtype='float32')
    Converts a class vector (integers) to binary class matrix.
    
    E.g. for use with categorical_crossentropy.
    
    Arguments:
        y: class vector to be converted into a matrix
            (integers from 0 to num_classes).
        num_classes: total number of classes. If `None`, this would be inferred
          as the (largest number in `y`) + 1.
        dtype: The data type expected by the input. Default: `'float32'`.
    
    Returns:
        A binary matrix representation of the input. The classes axis is placed
        last.
    
    Example:
    
    >>> a = tf.keras.utils.to_categorical([0, 1, 2, 3], num_classes=4)
    >>> a = tf.constant(a, shape=[4, 4])
    >>> print(a)
    tf.Tensor(
      [[1. 0. 0. 0.]
       [0. 1. 0. 0.]
       [0. 0. 1. 0.]
       [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)
    
    >>> b = tf.constant([.9, 

In [15]:
# df_train.describe()

,feature_intelligence1,feature_intelligence2,feature_intelligence3,feature_intelligence4,feature_intelligence5,feature_intelligence6,feature_intelligence7,feature_intelligence8,feature_intelligence9,feature_intelligence10,feature_intelligence11,feature_intelligence12,feature_charisma1,feature_charisma2,feature_charisma3,feature_charisma4,feature_charisma5,feature_charisma6,feature_charisma7,feature_charisma8,feature_charisma9,feature_charisma10,feature_charisma11,feature_charisma12,feature_charisma13,feature_charisma14,feature_charisma15,feature_charisma16,feature_charisma17,feature_charisma18,feature_charisma19,feature_charisma20,feature_charisma21,feature_charisma22,feature_charisma23,feature_charisma24,feature_charisma25,feature_charisma26,feature_charisma27,feature_charisma28,...,feature_wisdom8,feature_wisdom9,feature_wisdom10,feature_wisdom11,feature_wisdom12,feature_wisdom13,feature_wisdom14,feature_wisdom15,feature_wisdom16,feature_wisdom17,feature_wisdom18,feature_wisdom19,feature_wisdom20,feature_wisdom21,feature_wisdom22,feature_wisdom23,feature_wisdom24,feature_wisdom25,feature_wisdom26,feature_wisdom27,feature_wisdom28,feature_wisdom29,feature_wisdom30,feature_wisdom31,feature_wisdom32,feature_wisdom33,feature_wisdom34,feature_wisdom35,feature_wisdom36,feature_wisdom37,feature_wisdom38,feature_wisdom39,feature_wisdom40,feature_wisdom41,feature_wisdom42,feature_wisdom43,feature_wisdom44,feature_wisdom45,feature_wisdom46,target
count,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,...,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000,501808.000000
mean,0.499981,0.499979,0.499979,0.499981,0.499977,0.499977,0.499977,0.499981,0.499980,0.499980,0.499981,0.499977,0.499968,0.499976,0.499974,0.499977,0.499976,0.499971,0.499974,0.499974,0.499986,0.499977,0.499979,0.499980,0.499977,0.499972,0.499974,0.499977,0.499977,0.499974,0.499968,0.499981,0.499983,0.499979,0.499977,0.499976,0.499982,0.499981,0.499976,0.499976,...,0.499982,0.499973,0.499969,0.499976,0.499971,0.499978,0.499981,0.499979,0.499979,0.499981,0.499969,0.499969,0.499981,0.499974,0.499973,0.499976,0.499974,0.499969,0.499982,0.499979,0.499974,0.499981,0.499979,0.499979,0.499976,0.499974,0.499978,0.499981,0.499982,0.499979,0.499982,0.499982,0.499974,0.499980,0.499982,0.499980,0.499974,0.499979,0.499971,0.499997
std,0.353596,0.353593,0.353593,0.353596,0.353587,0.353587,0.353587,0.353596,0.352099,0.352099,0.353596,0.353587,0.352986,0.334986,0.337437,0.338557,0.313514,0.353014,0.320992,0.291361,0.353473,0.348416,0.343023,0.343407,0.340066,0.336707,0.291361,0.337442,0.338557,0.353060,0.352986,0.343146,0.341998,0.288122,0.333733,0.334986,0.265371,0.339712,0.288295,0.344535,...,0.350824,0.353485,0.349533,0.332947,0.353419,0.344672,0.353596,0.353143,0.347689,0.353596,0.351413,0.349533,0.353596,0.348778,0.353485,0.302390,0.341651,0.351413,0.350824,0.353143,0.348778,0.353596,0.347689,0.352772,0.302390,0.341651,0.344672,0.353596,0.352151,0.352772,0.353139,0.353139,0.351328,0.350662,0.35